# This workflow now builds T3000Controls and BACnetStackLibrary components

name: Release

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: cmake
        run: |
          cd ${{ github.workspace }}
          cd build
          cmake -A Win32 .. -DCMAKE_TOOLCHAIN_FILE="..\vcpkg-export-openssl\scripts\buildsystems\vcpkg.cmake"

      - name: cmake-build
        run: |
          echo CMake configuration successful. Going for build...
          cd build
          cmake --build . --config Release

      - name: Build webview assets
        run: |
          cd t3-webview-ui
          npm install
          npm run build
          xcopy "dist\spa\" "..\T3000\ResourceFile\webview\www\" /E /H /C /I

      - name: Build AIP
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-version: "20.8"
          advinst-enable-automation: "true"
          aip-path: ${{ github.workspace }}\T3000.aip
          aip-build-name: DefaultBuild
          aip-package-name: T3000-installer.msi
          aip-output-dir: ${{ github.workspace }}\setup
          aip-commands: |
            AddFolder "APPDIR" ".\T3000\ResourceFile"
            AddFolder "APPDIR" ".\build\bin\Release" -install_in_parent_folder
            SetVersion -increment
      - name: Publish setup artifact
        uses: actions/upload-artifact@v3
        with:
          name: setup
          path: ${{ github.workspace }}\setup\T3000-installer.msi

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}\setup\T3000-installer.msi
          asset_name: ${{ github.event.repository.name }}.msi
          asset_content_type: application/x-ms-installer
